### ISSUE TITLE
Moogle Dailies

### ISSUE THREAD

**Issue by Sno-sno** [sodimm/RebornBuddy#2]
Having some issues when it mounts up. It's moving before it can actually full load onto the mount. Cycles till latency proves long enough for the game to mount me (Perhaps add in a short delay to ensure user is mounted before moving?)

An Ishguardian Treat, Seems to fail turning in during the initial cycle, have to start the profile twice for it to turn it all in.

**Comment by sodimm** [comment]
i'll add a longer wait before the mounted check, i've noticed this too at high latency, the game reports mounted, but the client isn't. Ishgardian treat i'll have a look at when it pops for me. Thanks for the report.

**Comment by sodimm** [comment]
In the time being. If anyone reading this can check the ItemId of the Key Item required for "An Ishgardian Treat" please post it here. I'm guessing they've changed as it no longer exists on xivdb.

**Comment by sodimm** [comment]
mount issue should be fixed in new revision, still waiting on ishgardian treat quest. could be a few things not just hasitems, as it's working for everything else just not ishgardian treat. so i'm thinking it may be objective/step/count issue.

**Comment by Sno-sno** [comment]
Just saw your notification on discord. I'm still having this issue (I am up to date)

**Comment by sodimm** [comment]
yeah i'm unable to diagnose until i'm resubbed. hopefully not too long. i've taken another look at the hasitems code and there's no feasable reason why it doesn't work for this one quest.

**Comment by Sno-sno** [comment]
Should have clarified, I'm referring to the mounting issue

**Comment by sodimm** [comment]
fixed in restructure
